name: obi
on:
  workflow_dispatch:
#    branches:
#      - test
#  push:
#    branches:
#      - test
    inputs:
      filename:
        description: 'env file name'
        required: true
      number:
        description: 'env file name'
        required: true

env:
  TEST01: ${{ github.event.inputs.filename }}
  
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello jobs
        env:
          test_01: "test_01"
          test_02: "test_02"
          FILENAME: ${{ github.event.inputs.filename }}
          NUMBER: ${{ github.event.inputs.number }} 
        run: |
          echo "this is main"
          echo $TEST01
          cat test.txt
          touch env.${{ github.event.inputs.filename }}.txt
          ls -l
          if [ "$FILENAME" = "dev" ] && [ "$NUMBER" = 1 ]; then
            echo $test_01
          elif [ "$FILENAME" = "prod" ] && [ "$NUMBER" = 2 ]; then
            echo $test_02
          fi
