name: obi
on:
  workflow_dispatch:
#    branches:
#      - test
#  push:
#    branches:
#      - test
    inputs:
      filename:
        description: 'env file name'
        required: true
        default: ''
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello jobs
        run: |
          echo "this is main"
          cat test.txt
          touch env.${{ github.event.inputs.filename }}.txt
          ls -l
