name: obi
on:
  workflow_dispatch:
#    branches:
#      - test
#  push:
#    branches:
#      - test

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello jobs
        run: |
          echo "this is test"
          cat test.txt
