name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'username'
        required: false
        default: 'Obi'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 30
          echo "Hello ${{ github.event.inputs.name }}!"
